version: "3.9"
services:
  ocm-db:
    container_name: postgis
    image: postgis/postgis
    environment:
      - POSTGRES_DB=freeman
      - POSTGRES_USER=freeman
      - POSTGRES_PASSWORD=freeman
    ports:
      - "5432:5432"
  ocm-osmutils:
    container_name: ocm-osm2pgsql
    build: .
#    volumes:
#      - /osm2pgsql/data:/home/freeman/PycharmProjects/osm-charging-station-analysis/data
