version: "3.9"
services:
  ocm-prod-db:
    container_name: ocm-prod-db
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=freeman_prod
      - POSTGRES_USER=freeman_prod
      - POSTGRES_PASSWORD=freeman_prod
    ports:
      - "5432:5432"
  ocm-process-db:
    container_name: ocm-process-db
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=freeman_process
      - POSTGRES_USER=freeman_process
      - POSTGRES_PASSWORD=freeman_process
    ports:
      - "25432:5432"
  ocm-process:
    container_name: ocm-process
    build: .
